; File parsed and cached on [2025:08:23] at [13:18:02]

; File parsed and cached on [2025:08:23] at [13:17:54]

; File parsed and cached on [2025:08:23] at [13:15:35]

; File parsed and cached on [2025:08:23] at [13:15:02]

; File parsed and cached on [2025:08:23] at [12:57:14]

; File parsed and cached on [2025:08:23] at [12:56:14]

; File parsed and cached on [2025:08:23] at [12:55:53]

; File parsed and cached on [2025:08:23] at [12:33:54]

; File parsed and cached on [2025:08:04] at [22:14:16]

; This is a test comment
[owner]
name = John Doe
organization = Big Money Corp.

[database]
; This is the second test comment
server = 192.0.2.62
port = 143
file = payroll.dat